// Objective-C API for talking to github.com/goany/mobile Go package.
//   gobind -lang=objc github.com/goany/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Unichain_H__
#define __Unichain_H__

@import Foundation;
#include "Universe.objc.h"


@class UnichainETHWallet;

@interface UnichainETHWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)address;
- (NSData*)encrypt:(NSString*)password error:(NSError**)error;
- (NSString*)mnemonic:(NSError**)error;
- (NSData*)transferCurrency:(NSString*)nonceString gasPriceString:(NSString*)gasPriceString to:(NSString*)to amountString:(NSString*)amountString error:(NSError**)error;
- (NSData*)transferToken:(NSString*)nonceString gasPriceString:(NSString*)gasPriceString contract:(NSString*)contract data:(NSData*)data error:(NSError**)error;
@end

FOUNDATION_EXPORT UnichainETHWallet* UnichainETHWalletFromMnemonic(NSString* mnemonic, NSError** error);

FOUNDATION_EXPORT UnichainETHWallet* UnichainNewETHWallet(NSError** error);

#endif
